### ISSUE TITLE
Feature Request: Add ReplaceHeader and ReplaceFooter function

### ISSUE THREAD

**Issue by kokizzu** [nguyenthenguyen/docx#3]
there is a need to replace header and footer text

**Comment by AnnAddicks** [comment]
+1 for a replace header text.

I'd be happy to help with some initial direction.

**Comment by nguyenthenguyen** [comment]
Sorry for a long time I'm not watching this repository. @AnnAddicks Could you add replace footer and some unit test ?

**Comment by AnnAddicks** [comment]
Sure, I'd be happy to work on it; earliest time I would be able to push code would be Sunday evening.

**Comment by AnnAddicks** [comment]
Hi @nguyenthenguyen, 
I just sat down to look at the footers and noticed a change to the ReplaceHeader function.  If we are taking a user input for how many replaces should be done, is that per header or total?  With the new changes that limits the number of changes to per header because we don't keep track of how many times it has been changed inside the loop.  That is why initially I had it to not allow the user to pick a number.

I can make the footer code similar to what you have changed, but wanted to point this out.  It would be a PITA to keep track per header since Replace doesn't return a count.

**Comment by nguyenthenguyen** [comment]
@AnnAddicks You are right! Because we can have mutiple header, footer file. You can remove `num` params on `ReplaceHeader` and do the same for `ReplaceFooter`
